### ISSUE TITLE
Panics when reconciling resources with empty `MyResourceStatus` struct

### ISSUE THREAD

**Issue by mamachanko** [vmware-labs/reconciler-runtime#186]
`reconciler-runtime` panics when reconciling a resource with an empty status struct.

I have created https://github.com/mamachanko/reconciler-runtime-empty-status to reproduce the issue.

See [`ThingStatus` before](https://github.com/mamachanko/reconciler-runtime-empty-status/blob/5296e9ed3f73790484652f80ba614d62b2e39ddc/api/v1alpha1/thing_types.go#L23-L27) resolving the issue by inlining `apis.Status` and [after](https://github.com/mamachanko/reconciler-runtime-empty-status/blob/main/api/v1alpha1/thing_types.go#L24-L30).

[This is what the dummy reconciler looks like.](https://github.com/mamachanko/reconciler-runtime-empty-status/blob/main/controllers/thing_controller.go#L13-L31)

When running the controller and applying a `Thing`, e.g. `kubectl apply -f config/samples` it fails as follows:
```
❯ go run .
I0210 09:45:12.719992   79231 request.go:665] Waited for 1.03863609s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:59565/apis/extensions/v1beta1?timeout=32s
1.644482712823977e+09   INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
1.64448271282433e+09    INFO    setup   starting manager
1.644482712824439e+09   INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
1.6444827128244538e+09  INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
1.644482712824589e+09   INFO    controller.thing        Starting EventSource    {"reconciler group": "mamachanko.com", "reconciler kind": "Thing", "source": "kind source: *v1alpha1.Thing"}
1.6444827128246279e+09  INFO    controller.thing        Starting Controller     {"reconciler group": "mamachanko.com", "reconciler kind": "Thing"}
1.644482712925227e+09   INFO    controller.thing        Starting workers        {"reconciler group": "mamachanko.com", "reconciler kind": "Thing", "worker count": 1}
1.644482714103529e+09   INFO    controllers.Thing.Thing.ThingSync       syncing...
panic: reflect: call of reflect.Value.SetInt on zero Value

goroutine 363 [running]:
reflect.flag.mustBeAssignableSlow(0x0)
        /usr/local/Cellar/go/1.17.6/libexec/src/reflect/value.go:255 +0x116
reflect.flag.mustBeAssignable(...)
        /usr/local/Cellar/go/1.17.6/libexec/src/reflect/value.go:249
reflect.Value.SetInt({0x0, 0x0, 0xc00068a500}, 0x1)
        /usr/local/Cellar/go/1.17.6/libexec/src/reflect/value.go:1991 +0x48
github.com/vmware-labs/reconciler-runtime/reconcilers.(*ParentReconciler).copyGeneration(0xc00073a3f0, {0x24abe68, 0xc00068a500})
        /*****/go/pkg/mod/github.com/vmware-labs/reconciler-runtime@v0.4.0/reconcilers/reconcilers.go:166 +0x1a5
github.com/vmware-labs/reconciler-runtime/reconcilers.(*ParentReconciler).reconcile(0xc000452780, {0x2464778, 0xc0005efad0}, {0x24abe68, 0xc00068a500})
        /*****/go/pkg/mod/github.com/vmware-labs/reconciler-runtime@v0.4.0/reconcilers/reconcilers.go:154 +0xa5
github.com/vmware-labs/reconciler-runtime/reconcilers.(*ParentReconciler).Reconcile(0xc000452780, {0x2464778, 0xc0005ef980}, {{{0xc0006ab9e0, 0x7}, {0xc0006ab9d0, 0xc}}})
        /*****/go/pkg/mod/github.com/vmware-labs/reconciler-runtime@v0.4.0/reconcilers/reconcilers.go:120 +0x51c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000234fd0, {0x2464778, 0xc0005ef8c0}, {{{0xc0006ab9e0, 0x21a40a0}, {0xc0006ab9d0, 0x10151d4}}})
        /*****/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000234fd0, {0x24646d0, 0xc00091c880}, {0x20fb200, 0xc00074a680})
        /*****/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000234fd0, {0x24646d0, 0xc00091c880})
        /*****/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /*****/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /*****/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x357
exit status 2
```

It makes sense to expect a non-empty status struct, but its not mentioned in the README and might trip people up. I found the solution by looking at `FunctionStatus` [over here](https://github.com/projectriff/system/blob/1f5e964d5450cbb3dcc9ce579fcbce48da6be8f1/pkg/apis/build/v1alpha1/function_types.go#L77-L84).

**Comment by mamachanko** [comment]
Possible duplicate of #108. Feel free to close.
